baseURL = 'https://rcs0816.org'
languageCode = 'en-us'
title = 'The Revolutionary Committee of S08-16'
title_short = 'The RCS08-16'
theme = "roxo-hugo-custom"
summarylength = 25

# some menus
[menu]
    [[menu.nav]]
    name = "Home"
    url = ""
    weight = 1

    [[menu.nav]]
    name = "About Us"
    url = "about-us"
    weight = 2

    [[menu.nav]]
    name = "Our Imapact"
    url = "our-impact"
    weight = 3

    [[menu.nav]]
    name = "The Corner of Enlightenment"
    url = "the-coe"
    weight = 5

[params]
    logo = "/images/RCSLogo-wide.png"
    logo_footer = "/images/RCSImage.png"
    favicon_icon = "/images/favicon.ico"
    favicon_shortcut_icon = "/images/RCSLogo-monochrome.png"
    dateFormat = "26 FEB 1994"
    description = "The Revolutionary Committee of S08-16"
    author = "RCS08-16"
    copyright_text = "All rights reserved by"
    copyright_link = "https://rcs0816.org/about-us"
    copyright_name = "the members of RCS08-16"
    
    [params.navAction]
        enable = true
        name = "Get In Touch"
        url = "get-in-touch"
    
    [params.banner]
        enable = true
        background_image = "/images/RCSImage.jpg"
        heading = "Embracing students' freedom, Protecting S08-16"
        tagline = "RAIFA S08-16, HE RAIFA HORÏSONI KYEDOQARRÉYAZ ALÉSRA!"
        primary_button = "About Us"
        primary_button_url = "about-us"
        secondary_button = "The Corner of Enlightenment"
        secondary_button_url = "the-coe"
    
    [params.blog]
        enable = true
        read_more = "read more"

    [params.portfolio]
        enable = true
        title = "What we've done"
        subtitle = """Our mission is to protect the spirit of S08-16 like when it was first created.
                    We ensure the happiness of everybody who chooses to dwell in our room, provide fun
                    activities, and give the students the full right to voice their concerns via the 
                    corner of enlightenment. Our achievements also include the reduction of exam papers,
                    more freedom for the G12 seniors' committee, and the defense of S08-16 against
                    a communist revolution by the OFS Students' Communist Party (now defunct)."""
        view_project = ""
        more_works = ""
        scroll_down = "scroll down"
    
    [params.call_to_action]
        enable = true # TODO: take sexy images
        background_image = "/images/Whiteboard.jpg"        
        title = "WE NEED YOU!"
        primary_button = "Contact our team for Applications"
        primary_button_url = "about-us"
        secondary_button = "But I'm a filthy commie ☭ ..."
        secondary_button_url = "go-to-hell"

    [params.footer]
        qt_print = false

        [params.footer.back_to_top]
            description = "go back to the top"
     
        [params.footer.contactInfo]
            title = "Contact Information"
            address = "13 Tansha St.,<br>#02-01 Kourisa Household<br>Distaye, Southbridge District,<br>Sitaku City, Second Creative, Republic of Sitaku"
            email = "horison.rcs0816@gmail.com"
        
        [params.footer.sitemap]
            title = "Sitemap"
            [[params.footer.sitemap.link]]
                name = "About Us"
                url = "about-us"
            [[params.footer.sitemap.link]]
                name = "Our Impact"
                url = "our-impact"
            [[params.footer.sitemap.link]]
                name = "The Corner of Enlightenment"
                url = "the-coe"
